import { Geist, Geist_Mono } from "next/font/google"
import NavBar from "@/components/NavBar"
import Footer from "@/components/Footer"
import "./globals.css"
import { CartProvider } from "./context/cartcontext"  // Adjust path as needed
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <NavBar />
          {children}
          <Footer />
          <Toaster position="top-right" reverseOrder={false} />
        </CartProvider>
      </body>
    </html>
  )
}
